import Login from "@/components/Login/Login";
import Head from "next/head";

export default function LoginPage() {
	return (
		<>
			<Head>
				<title>Simple Kanban</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Login type="login" />
		</>
	);
}
