import Login from "@/components/Login/Login";
import Head from "next/head";

import { getSession } from "next-auth/react";

export default function LoginPage() {
	return (
		<>
			<Head>
				<title>Simple Kanban</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Login type="login" />
		</>
	);
}

export async function getServerSideProps(context) {
	const session = await getSession({ req: context.req });

	if (!session) {
		return;
	}

	return {
		props: { session },
		redirect: {
			destination: "/boards",
		},
	};
}
